name: Deploy BE

on:
  push:
    branches: [ main ]

jobs:
  deploy-laravel:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Update
        run: |
          curl -i -X POST https://mogamogapecahtelor.faaruq.com/laravel \
            -H "Authorization: Bearer ${{ secrets.API_PASSWORD }}" \
            -H "Content-Type: application/json" \
            -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
